debug: true
spring:
  session:
    store-type: redis
  resources:
    cache-period: 604800
    chain: 
      gzipped: false
      cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    mode: html
  http:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    dialect: org.hibernate.dialect.*.MySQLDialect
  datasource:
    schema: 
      - classpath:/META-INF/schema/schema-usm.sql
    data: 
#      - classpath:/sql/data-usm.sql
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid: 
      url: jdbc:mysql://localhost:3306/jusm?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456 
      initial-size: 10 
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        filter: 
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall: 
            config:
              multi-statement-allow: true  
  redis:   ######redis#####
      database: 0
      host: localhost
      port: 6379
      password: 123456     # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
usm:
  swagger:
    email: swagger-admin@master.com       
  ant-pattern:
    authorize-ant-patterns: "/api/**"    
    rest-ant-pattern: "/api/**"    

 